[package]
name = "charta"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
rmcp = { version = "1.5.0", features = ["server", "macros", "transport-io"] }
schemars = "1.2.1"
scxml = "0.1.0"
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.27.0"
thiserror = "2.0.18"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "process"] }
z3 = "0.20.0"
