//! MCP server handler and tool router for charta.
//!
//! [`Charta`] is the single `ServerHandler` implementation exposed to clients.
//! It registers three tools via the `#[tool_router]` / `#[tool]` macro pair
//! from `rmcp`:
//!
//! * `validate_state_chart`  — parse + structurally validate SCXML.
//! * `visualise_state_chart` — render valid SCXML as a Mermaid diagram.
//! * `codegen_state_chart`   — shell out to `sce-codegen` and return generated
//!   source files as text content blocks.

use std::io::Write;

use rmcp::{
    ErrorData, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, Content, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router,
};
use tokio::process::Command;

use scxml::{export, parse_xml, validate};

use crate::tools::{
    CodegenStateChart, ToolError, ValidateStateChart, VisualiseStateChart,
};

/// MCP server handler for charta.
///
/// `tool_router` is generated by the `#[tool_router]` macro and dispatches
/// incoming `tools/call` requests to the right method below. The struct is
/// `Clone` because `rmcp` may clone the handler per-session.
#[derive(Clone)]
pub struct Charta {
    /// Tool dispatch table built from the `#[tool]`-annotated methods.
    pub tool_router: ToolRouter<Self>,
}

impl Default for Charta {
    /// Build a fresh handler with the macro-generated tool router wired in.
    fn default() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }
}

#[tool_router]
impl Charta {
    /// `validate_state_chart` — parse and structurally validate SCXML XML.
    ///
    /// Returns the literal text `"OK"` on success. Parse / validation
    /// failures surface as `invalid_params` JSON-RPC errors via
    /// [`ToolError`](crate::tools::ToolError).
    #[tool(
        description = "Validate a state chart XML. Returns OK if valid, otherwise returns an error message."
    )]
    pub async fn validate_state_chart(
        &self,
        Parameters(ValidateStateChart { state_chart }): Parameters<ValidateStateChart>,
    ) -> Result<CallToolResult, ErrorData> {
        // Two-phase check: first ensure the XML parses into the SCXML AST,
        // then run semantic validation (state IDs resolve, transitions point
        // at real targets, etc.).
        let chart = parse_xml(&state_chart).map_err(ToolError::Parse)?;
        validate(&chart).map_err(ToolError::Validate)?;
        Ok(CallToolResult::success(vec![Content::text(format!("OK"))]))
    }

    /// `visualise_state_chart` — render valid SCXML as a Mermaid diagram.
    ///
    /// The result is a single text content block containing Mermaid syntax
    /// suitable for pasting into any Mermaid-aware renderer.
    #[tool(
        description = "Visualise a valid state chart XML as a Mermaid diagram. Returns the Mermaid syntax for the diagram."
    )]
    pub async fn visualise_state_chart(
        &self,
        Parameters(VisualiseStateChart { state_chart }): Parameters<VisualiseStateChart>,
    ) -> Result<CallToolResult, ErrorData> {
        // Same validate-before-use guard as `validate_state_chart`: we never
        // try to render a chart we haven't proven is structurally sound.
        let chart = parse_xml(&state_chart).map_err(ToolError::Parse)?;
        validate(&chart).map_err(ToolError::Validate)?;

        // `to_mermaid` is infallible on a validated chart.
        let dot = export::mermaid::to_mermaid(&chart);
        Ok(CallToolResult::success(vec![Content::text(dot)]))
    }

    /// `codegen_state_chart` — generate source code for the requested backend
    /// by shelling out to the `sce-codegen` binary.
    ///
    /// Workflow:
    /// 1. Validate the SCXML (so we don't spawn a subprocess for bad input).
    /// 2. Write the SCXML into a fresh tempdir.
    /// 3. Invoke `sce-codegen generate <input> -l <backend> -o <out_dir>`.
    /// 4. Read every file the tool produced and return them as labelled
    ///    text content blocks (one per generated file).
    ///
    /// The tempdir is automatically removed when `workdir` drops at the end
    /// of the function.
    #[tool(
        description = "Generate source code from an SCXML state chart for a target backend. Supported backends: rust, go, cpp, kotlin, c11. Returns the generated code as text. Requires the `sce-codegen` binary on PATH (override with SCE_CODEGEN_BIN)."
    )]
    pub async fn codegen_state_chart(
        &self,
        Parameters(CodegenStateChart {
            state_chart,
            backend,
        }): Parameters<CodegenStateChart>,
    ) -> Result<CallToolResult, ErrorData> {
        // Fail fast on bad SCXML before spawning a subprocess.
        let chart = parse_xml(&state_chart).map_err(ToolError::Parse)?;
        validate(&chart).map_err(ToolError::Validate)?;

        // Scratch space for the input file and any generated output. Dropped
        // (and recursively deleted) when this function returns.
        let workdir = tempfile::tempdir().map_err(ToolError::Io)?;
        // `sce-codegen` derives output filenames from the input file stem,
        // so pinning it to "chart" gives us deterministic names like
        // `chart_sm.rs`, `chart_sm.go`, `chart_sm.h`, etc.
        let stem = "chart";
        let scxml_path = workdir.path().join(format!("{stem}.scxml"));
        {
            // Inner scope so the file handle is flushed/closed before the
            // subprocess opens the same path.
            let mut f = std::fs::File::create(&scxml_path).map_err(ToolError::Io)?;
            f.write_all(state_chart.as_bytes()).map_err(ToolError::Io)?;
        }

        // Allow operators to override the binary location (e.g. when
        // `sce-codegen` is not on PATH inside a sandboxed MCP host).
        let bin = std::env::var("SCE_CODEGEN_BIN").unwrap_or_else(|_| "sce-codegen".into());
        let out_dir = workdir.path().join("out");
        std::fs::create_dir_all(&out_dir).map_err(ToolError::Io)?;

        // Spawn `sce-codegen generate <scxml> -l <lang> -o <out_dir>`.
        // We wait synchronously for it to finish and capture stdout/stderr.
        let output = Command::new(&bin)
            .arg("generate")
            .arg(&scxml_path)
            .arg("-l")
            .arg(backend.as_flag())
            .arg("-o")
            .arg(&out_dir)
            .output()
            .await
            .map_err(|e| {
                // Translate "no such file" specifically so the caller sees
                // the actionable `BinaryNotFound` message instead of a
                // generic I/O error.
                if e.kind() == std::io::ErrorKind::NotFound {
                    ToolError::BinaryNotFound
                } else {
                    ToolError::Io(e)
                }
            })?;

        // Surface non-zero exits with the captured stderr so debugging
        // bad SCXML / unsupported features is straightforward.
        if !output.status.success() {
            return Err(ToolError::CodegenFailed(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            )
            .into());
        }

        // Collect every generated file (rust/go = 1 file, cpp = 2 files).
        let mut contents = Vec::new();
        let entries = std::fs::read_dir(&out_dir).map_err(ToolError::Io)?;
        // Filter to regular files and sort for stable, reproducible output
        // ordering across platforms / filesystems.
        let mut files: Vec<_> = entries
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_file())
            .collect();
        files.sort_by_key(|e| e.path());
        for entry in files {
            let path = entry.path();
            // Best-effort filename extraction; non-UTF-8 names fall back to
            // a placeholder rather than failing the whole call.
            let name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("<unknown>")
                .to_string();
            let body = std::fs::read_to_string(&path).map_err(ToolError::Io)?;
            // Each file gets its own content block, prefixed with a
            // `// === <name> ===` banner so multi-file backends (cpp, c11)
            // remain trivially separable on the client side.
            contents.push(Content::text(format!("// === {name} ===\n{body}")));
        }

        // Defensive: if `sce-codegen` exited 0 but produced nothing, treat
        // it as a codegen failure rather than returning an empty success.
        if contents.is_empty() {
            return Err(ToolError::CodegenFailed(format!(
                "sce-codegen produced no files for backend {:?}",
                backend
            ))
            .into());
        }

        Ok(CallToolResult::success(contents))
    }
}

/// MCP `ServerHandler` glue. The `#[tool_handler]` macro wires the generated
/// `tool_router` into the trait's `tools/list` and `tools/call` plumbing.
#[tool_handler(router = self.tool_router)]
impl ServerHandler for Charta {
    /// Advertise capabilities and a human-readable instructions string at
    /// session start. We only enable tools — no resources, prompts, or
    /// sampling support is offered by this server.
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_instructions(
                "charta MCP server. Tools: validate_state_chart, visualise_state_chart, codegen_state_chart.",
            )
    }
}
